"use client";

import Link from "next/link";
import { useCallback, useEffect, useMemo, useState } from "react";
import { apiFetch } from "@/lib/api-client";
import { ConversationItem, label, riskClass } from "@/lib/operations";
import { OperationsState } from "@/components/OperationsState";

export default function SignalRadarPage() {
  const [items,setItems]=useState<ConversationItem[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState(""); const [risk,setRisk]=useState("all"); const [channel,setChannel]=useState("all"); const [query,setQuery]=useState("");
  const load=useCallback(async()=>{setLoading(true);setError("");try{setItems((await apiFetch<{items:ConversationItem[]}>("/signals/radar")).items)}catch(e){setError(e instanceof Error?e.message:"Could not load radar.")}finally{setLoading(false)}},[]);
  useEffect(()=>{void load()},[load]);
  const filtered=useMemo(()=>items.filter(item=>(risk==="all"||item.riskLevel===risk)&&(channel==="all"||item.channel===channel)&&item.youthName.toLowerCase().includes(query.toLowerCase())),[items,risk,channel,query]);
  return <div className="space-y-5"><section className="rounded-[28px] border border-slate-200 bg-white p-6"><p className="text-xs font-semibold uppercase tracking-[.2em] text-pine">Signal Radar</p><h2 className="mt-2 text-3xl font-semibold">Explainable priority signals</h2><div className="mt-4 grid gap-2 sm:grid-cols-3"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search youth" className="rounded-xl border px-3 py-2 text-sm"/><select value={risk} onChange={e=>setRisk(e.target.value)} className="rounded-xl border px-3 py-2 text-sm"><option value="all">All risks</option>{["critical","high","medium","low"].map(v=><option key={v}>{v}</option>)}</select><select value={channel} onChange={e=>setChannel(e.target.value)} className="rounded-xl border px-3 py-2 text-sm"><option value="all">All channels</option>{Array.from(new Set(items.map(i=>i.channel))).map(v=><option key={v}>{v}</option>)}</select></div></section><OperationsState loading={loading} error={error} empty={!filtered.length} retry={load}><section className="grid gap-4 lg:grid-cols-2">{filtered.map(item=><article key={item.id} className="rounded-2xl border bg-white p-5"><div className="flex justify-between gap-3"><div><h3 className="font-semibold text-ink">{item.youthName}</h3><p className="text-xs text-slate-500">{item.channel}</p></div><span className={`h-fit rounded-full px-3 py-1 text-xs font-semibold ${riskClass(item.riskLevel)}`}>{label(item.riskLevel)} {item.riskScore}</span></div><ul className="mt-4 space-y-2">{item.signals.map(s=><li key={s.id} className="rounded-xl bg-slate-50 p-3 text-sm"><strong>{label(s.type)}:</strong> {s.reason}<span className="ml-2 text-xs text-slate-400">{s.source}</span></li>)}</ul><Link href={`/worker/youths/${item.youthId}`} className="mt-4 inline-block text-sm font-semibold text-pine">Open context →</Link></article>)}</section></OperationsState></div>;
}
