"use client";

import Link from "next/link";
import { useCallback,useEffect,useMemo,useState } from "react";
import { apiFetch } from "@/lib/api-client";
import { ConversationItem,riskClass,label } from "@/lib/operations";
import { OperationsState } from "@/components/OperationsState";

export default function ProfilesPage(){const[items,setItems]=useState<ConversationItem[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState("");const load=useCallback(async()=>{setLoading(true);try{setItems((await apiFetch<{conversations:ConversationItem[]}>("/worker/cockpit")).conversations);setError("")}catch(e){setError(e instanceof Error?e.message:"Could not load profiles")}finally{setLoading(false)}},[]);useEffect(()=>{void load()},[load]);const profiles=useMemo(()=>Array.from(new Map(items.map(i=>[i.youthId,i])).values()),[items]);return <div className="space-y-5"><section className="rounded-[28px] border bg-white p-6"><p className="text-xs font-semibold uppercase tracking-[.2em] text-pine">Youth context</p><h2 className="mt-2 text-3xl font-semibold">Memory cards for continuity of care.</h2></section><OperationsState loading={loading} error={error} empty={!profiles.length} retry={load}><section className="grid gap-4 lg:grid-cols-2">{profiles.map(item=><Link key={item.youthId} href={`/worker/youths/${item.youthId}`} className="rounded-2xl border bg-white p-5 transition hover:border-pine"><div className="flex justify-between"><div><h3 className="text-lg font-semibold">{item.youthName}</h3><p className="text-sm text-slate-500">{item.channel}</p></div><span className={`h-fit rounded-full px-3 py-1 text-xs font-semibold ${riskClass(item.riskLevel)}`}>{label(item.riskLevel)}</span></div><p className="mt-3 text-sm text-slate-600">{item.suggestedAction}</p></Link>)}</section></OperationsState></div>}
