"use client";

import Link from "next/link";
import { useCallback,useEffect,useState } from "react";
import { apiFetch } from "@/lib/api-client";
import { Handoff,label,riskClass } from "@/lib/operations";
import { OperationsState } from "@/components/OperationsState";

export default function HandoffPreviewPage(){const[data,setData]=useState<Handoff|null>(null);const[loading,setLoading]=useState(true);const[error,setError]=useState("");const load=useCallback(async()=>{setLoading(true);try{const result=await apiFetch<{handoffs:Handoff[]}>("/youth/handoffs");setData(result.handoffs[0]||null);setError("")}catch(e){setError(e instanceof Error?e.message:"Could not load handoff note")}finally{setLoading(false)}},[]);useEffect(()=>{void load()},[load]);return <OperationsState loading={loading} error={error} empty={!data} retry={load}>{data?<div className="space-y-5"><section className="rounded-[28px] border bg-white p-6"><p className="text-xs font-semibold uppercase tracking-[.2em] text-pine">Your approved handoff note</p><div className="mt-2 flex flex-wrap justify-between gap-3"><h1 className="text-3xl font-semibold">Review what your worker can see</h1><span className={`h-fit rounded-full px-3 py-1 text-xs font-semibold ${riskClass(data.riskLevel)}`}>{label(data.riskLevel)}</span></div><p className="mt-3 text-sm text-slate-600">You remain in control and can choose what to add when your worker follows up.</p></section><section className="grid gap-4">{[["Main concern",data.mainConcern],["How the message sounded",data.emotionalState],["Your words",data.keyQuote],["What SafeNight did",data.whatAiDid],["What you should not need to repeat",data.whatNotToRepeat],["Recommended next step",data.recommendedNextStep]].map(([title,value])=><article key={title} className="rounded-2xl border bg-white p-4"><p className="text-xs font-semibold uppercase text-slate-500">{title}</p><p className="mt-2 text-sm leading-6 text-slate-700">{value}</p></article>)}</section><Link href="/youth/chat" className="inline-block rounded-xl bg-pine px-4 py-2 text-sm font-semibold text-white">Return to SafeNight</Link></div>:<div><Link href="/youth/chat">Start a chat to prepare a note</Link></div>}</OperationsState>}
