"use client";

import { FormEvent,useState } from "react";
import { useRouter } from "next/navigation";
import { login } from "@/lib/api-client";
import { getRoleHome,saveAuthSession } from "@/lib/auth-session";

const demos=[{label:"Mira · Youth",email:"mira@signalbridge.test"},{label:"Aisha · Worker",email:"worker1@signalbridge.test"},{label:"Daniel · Supervisor",email:"supervisor@signalbridge.test"}];
export default function LoginPage(){const router=useRouter();const[email,setEmail]=useState(demos[0].email);const[password,setPassword]=useState("password");const[loading,setLoading]=useState(false);const[error,setError]=useState("");async function submit(event:FormEvent){event.preventDefault();setLoading(true);setError("");try{const session=await login(email.trim().toLowerCase(),password);saveAuthSession(session);router.push(getRoleHome(session.user.role))}catch(e){setError(e instanceof Error?e.message:"Login failed")}finally{setLoading(false)}}return <main className="grid min-h-screen place-items-center bg-mist px-4 py-10"><section className="w-full max-w-lg rounded-[28px] border bg-white p-6 shadow-panel"><p className="text-xs font-semibold uppercase tracking-[.22em] text-pine">SignalBridge secure workspace</p><h1 className="mt-3 text-3xl font-semibold">Choose a fictional demo role</h1><p className="mt-2 text-sm text-slate-600">All roles authenticate against the API and are restricted again on every backend action.</p><div className="mt-5 grid gap-2 sm:grid-cols-3">{demos.map(d=><button key={d.email} onClick={()=>setEmail(d.email)} className={`rounded-xl border px-3 py-2 text-xs font-semibold ${email===d.email?"border-pine bg-pine text-white":"border-slate-200"}`}>{d.label}</button>)}</div><form onSubmit={submit} className="mt-5 grid gap-3"><label className="grid gap-1 text-sm font-medium">Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} className="rounded-xl border px-3 py-2"/></label><label className="grid gap-1 text-sm font-medium">Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} className="rounded-xl border px-3 py-2"/></label>{error?<p className="rounded-xl bg-coral/10 p-3 text-sm text-coral">{error}</p>:null}<button disabled={loading} className="rounded-xl bg-pine px-4 py-3 font-semibold text-white">{loading?"Signing in…":"Open workspace"}</button></form></section></main>}
