"use client";

import Link from "next/link";
import { useCallback,useEffect,useState } from "react";
import { apiFetch } from "@/lib/api-client";
import { ConversationItem,label,riskClass } from "@/lib/operations";
import { OperationsState } from "@/components/OperationsState";

export default function HandoffsPage(){const[items,setItems]=useState<ConversationItem[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState("");const load=useCallback(async()=>{setLoading(true);try{setItems((await apiFetch<{conversations:ConversationItem[]}>("/worker/cockpit")).conversations.filter(i=>i.handoffId&&i.consentToHandoff));setError("")}catch(e){setError(e instanceof Error?e.message:"Could not load handoffs")}finally{setLoading(false)}},[]);useEffect(()=>{void load()},[load]);return <div className="space-y-5"><section className="rounded-[28px] border bg-white p-6"><p className="text-xs font-semibold uppercase tracking-[.2em] text-pine">Consent-approved handoffs</p><h2 className="mt-2 text-3xl font-semibold">Start with context, not repetition.</h2></section><OperationsState loading={loading} error={error} empty={!items.length} retry={load}><section className="grid gap-4 lg:grid-cols-2">{items.map(item=><article key={item.id} className="rounded-2xl border bg-white p-5"><div className="flex justify-between"><h3 className="text-xl font-semibold">{item.youthName}</h3><span className={`rounded-full px-3 py-1 text-xs font-semibold ${riskClass(item.riskLevel)}`}>{label(item.riskLevel)}</span></div><p className="mt-3 text-sm text-slate-600">{item.suggestedAction}</p><Link href={`/worker/handoffs/${item.handoffId}`} className="mt-4 inline-block rounded-xl bg-pine px-4 py-2 text-sm font-semibold text-white">Review brief</Link></article>)}</section></OperationsState></div>}
